name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86_64-linux
        - aarch64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ github.token }}
      - uses: actions/checkout@v5
      - name: Build docker image
        run: |
          nix build .#${{ matrix.target }}.docker
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: result
  merge:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: ghcr.io/${{ github.repository_owner }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        set -x
        podman manifest create containers-storage:ghcr.io/majkrzak/playground:latest
        for artifact in build-*/result; do
          podman manifest add containers-storage:ghcr.io/majkrzak/playground:latest docker-archive:$artifact
        done
        podman manifest push --format=oci --all containers-storage:ghcr.io/majkrzak/playground:latest docker://ghcr.io/majkrzak/playground:latest
