name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - label: x86_64-linux
          os: ubuntu-24.04
        - label: aarch64-linux
          os: ubuntu-24.04-arm
    name: '${{ matrix.label }} build'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v5
      - name: Build docker image
        run: |
          nix build .#docker
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.label }}
          path: result
  merge:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        for artifact in build-*/result; do
          tag=$(docker load -i $artifact | grep -Go "playground:.*")
          all_tags="$all_tags ghcr.io/majkrzak/$tag"
          docker tag $tag ghcr.io/majkrzak/$tag
          docker push ghcr.io/majkrzak/$tag
          docker manifest rm ghcr.io/majkrzak/$tag
        done
        docker buildx imagetools create $all_tags --tag ghcr.io/majkrzak/playground:latest
